services:
  soc_app:
    build: .
    container_name: soc_system
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:13
    container_name: soc_db
    environment:
      POSTGRES_USER: soc_admin
      POSTGRES_PASSWORD: soc_password
      POSTGRES_DB: soc_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
